backend:
  name: git-gateway
  repo: pcesarteixeira/pauloteixeira.dev
  branch: master
  site_domain: pauloteixeira.dev

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Data de publicação", name: "date", widget: "datetime"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Artigo em destaque", name: "featuredpost", widget: "boolean"}
      - {label: "Imagem de capa", name: "cover", widget: image}
      - {label: "Artigo", name: "body", widget: "markdown"}